///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UploadFileOssEntity {


  String? accessid;
  String? policy;
  String? signature;
  String? dir;
  String? host;
  String? expire;
  String? ossUrl;

  UploadFileOssEntity({
    this.accessid,
    this.policy,
    this.signature,
    this.dir,
    this.host,
    this.expire,
    this.ossUrl,
  });
  UploadFileOssEntity.fromJson(Map<String, dynamic> json) {
    accessid = json["accessid"]?.toString();
    policy = json["policy"]?.toString();
    signature = json["signature"]?.toString();
    dir = json["dir"]?.toString();
    host = json["host"]?.toString();
    expire = json["expire"]?.toString();
    ossUrl = json["ossUrl"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["accessid"] = accessid;
    data["policy"] = policy;
    data["signature"] = signature;
    data["dir"] = dir;
    data["host"] = host;
    data["expire"] = expire;
    data["ossUrl"] = ossUrl;
    return data;
  }

  @override
  String toString() {
    return 'UploadFileOssEntity{accessid: $accessid, policy: $policy, signature: $signature, dir: $dir, host: $host, expire: $expire, ossUrl: $ossUrl}';
  }
}
