// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:riki_router/core/riki_route.dart';
import 'package:flutter/widgets.dart';
import 'package:riki_router/riki_router.dart';
import '../basics/event_bus_page.dart';
import '../main.dart';

// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import
RikiRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case '/':
      return RikiRouteSettings(
        name: name,
        arguments: arguments,
        widget: BottomTabBarPage(
          key: asT<Key?>(safeArguments['key']),
        ),
      );
    case '/event_bus_page':
      return RikiRouteSettings(
        name: name,
        arguments: arguments,
        widget: EventBusPage(
          key: asT<Key?>(safeArguments['key']),
        ),
        pageRouteType: PageRouteType.cupertino,
        description: 'EventBusPage',
      );
    default:
      return const RikiRouteSettings(name: '404', routeName: '404_page');
  }
}
