// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/cupertino  '/',
  '/event_bus_page',
];

class RikiRoutes {
  const RikiRoutes._();

  /// '/'
  ///
  /// [name] : '/'
  ///
  /// [constructors] :
  ///
  /// BottomTabBarPage : [Key? key]
  static const _Root root = _Root();

  /// 'EventBusPage'
  ///
  /// [name] : '/event_bus_page'
  ///
  /// [description] : 'EventBusPage'
  ///
  /// [constructors] :
  ///
  /// EventBusPage : [Key? key]
  ///
  /// [pageRouteType] : PageRouteType.cupertino
  static const _EventBusPage eventBusPage = _EventBusPage();
}

class _Root {
  const _Root();

  String get name => '/';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _EventBusPage {
  const _EventBusPage();

  String get name => '/event_bus_page';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}
