name: flutter_demo # *此属性表示包名（package name），此属性是非常重要的，引入其他文件时需要使用此包名
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1 # *此属性应用程序的版本和内部版本号，版本号 + 前面到部分，叫做 version number，由 2 个小点隔开，后面的部分叫做 build number。

environment: # *属性下添加 Flutter 和 Dart 版本控制。下面的版本规定此应用或库只能在高于或等于2.12.0，低于3.0.0的Dart SDK版本上运行。
  sdk: ">=2.12.0 <3.0.0"

# *dependencies 和 dev_dependencies
# *dependencies 和 dev_dependencies 下包含应用程序所依赖的包，dependencies 下的所有依赖会编译到项目中，而 dev_dependencies 仅仅是运行期间的包，比如自动生成代码的库。
# *我们可以通过四种方式依赖其包：
# *1. 依赖 pub.dev 上的第三方库
# *2. 依赖本地库
# *3. 依赖 git repository
# *4. 依赖我们自己的 pub仓库
dependencies:
  flutter:
    sdk: flutter

  imei_plugin:
    path: '../imei_plugin'
  riki_router:
    path: '../riki-router'
  riki_http:
    path: '../riki-http'
  riki_project_config:
    path: '../riki-project_config'
  ext_storage:
    path: '../riki_ext_storage-master'
  riki_uikit:
    path: '../riki-ui'
#  riki_webview:
#    path: '../riki-webview'

  intl: ">=0.17.0"

  dokit: ^0.8.0-nullsafety.0
  google_fonts: 2.1.0
  pull_to_refresh: ^2.0.0
  fluttertoast: ^7.1.4
  connectivity: 3.0.6
  shared_preferences: ^2.0.1
  oktoast: ^3.0.0
  provider: ^6.0.2
  #
  photo_manager: 1.3.10
  # 相册选择器 目前iOS用
  image_picker: 0.8.0+1
  # 仿微信图片选择框架
  wechat_assets_picker: ^6.0.0
  # 仿微信相机拍照
  wechat_camera_picker: 2.4.0
  # 存储图片到相册 image_gallery_saver
  image_gallery_saver: 1.7.1
  # 图片压缩
  flutter_image_compress: ^1.0.0
  # 视频压缩 https://github.com/jonataslaw/VideoCompress
  video_compress: ^3.1.0
  # 视频封面获取
  video_thumbnail: ^0.3.3
  # 动画文件播放器，支持svg  https://github.com/svga/SVGAPlayer-Flutter
  svgaplayer_flutter: ^2.1.1
  # 播放器插件
  #  audioplayers: ^0.19.0
  # 工具类
  flustars: ^2.0.1
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^6.0.6
  # 权限 https://github.com/baseflowit/flutter-permission-handler
  permission_handler: 8.1.6
  #
  device_info: ^2.0.2
  # uuid
  uuid: 3.0.5
  # 钥匙串
  flutter_keychain: 2.0.1
  # 状态栏 https://github.com/mchome/flutter_statusbarcolor
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  # 强制横屏
  orientation: ^1.3.0
  #
  flutter_staggered_grid_view: 0.3.4
  #
  flutter_cache_manager: 3.3.0
  # 打开本地文件
  open_file: ^3.2.1
  # 路径管理(https://pub.dev/packages/path_provider)
  path_provider: ^2.0.2
  # 侧滑菜单
  flutter_slidable: 0.6.0
  # 滑动到指定位置
  scroll_to_index: ^2.0.0
  # 获取滑动到位置
  inview_notifier_list: ^3.0.0
  # 生成二维码
  qr_flutter: ^4.0.0
  # 扫描二维码
  barcode_scan: ^2.0.2
  # Flutter汉字转拼音
  lpinyin: ^2.0.3
  #
  dart_ipify: 1.1.1
  # AzlistView
  # azlistview: ^2.0.0-nullsafety.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true # *确保您的应用程序中包含Material Icons字体，以便您可以使用material Icons类中的图标。

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/video/test.mp3
    - assets/images/head.jpg
    - assets/images/name.png
    - assets/kingset.svga
    - assets/angel.svga

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
